// app/layout.tsx
import { ConfigProvider } from 'antd';
import { designTokens } from '../styles/designTokens';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { sampleItems } from '@web/components/layout/MenuConfig';
import Topbar from '@web/components/layout/Topbar';
import { LogoutOutlined, MenuFoldOutlined, MenuUnfoldOutlined } from '@ant-design/icons';
import { Breadcrumb, Button, Layout, MenuProps } from 'antd';
import { User } from '@web/types/global';
import { useState } from 'react';
import Sidebar from '@web/components/layout/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const { Header, Content, Sider } = Layout;

const topbarItems: MenuProps['items'] = [
  { key: '1', label: 'Settings' },
  { key: '2', icon: <LogoutOutlined />, label: 'Logout' },
];

const sampleUser: User = {
  id: '1',
  name: 'Fiona Apple',
  role: 'user',
  company: 'Panca Prima Maju Bersama'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider
          theme={{
            token: designTokens,
          }}
        >
          <Layout>
            <Topbar user={sampleUser} topDropdownItems={topbarItems}/>
            <Layout style={{ height: 'calc(100vh - 64px)' }}>
              <Sidebar sideMenuItems={sampleItems}/>
              <Layout style={{ display: 'flex', flexDirection: 'column', flexGrow: 1 }}>
                {children}
              </Layout>
            </Layout>
          </Layout>
        </ConfigProvider>
      </body>
    </html>
  );
}

